# Generated by Django 6.1 on 2026-09-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('L', 'Lost'), ('F', 'Found')], max_length=1)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=128)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
