# Generated by Django 6.1 on 2026-09-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
    ]
