# Generated by Django 6.1 on 2026-09-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('resolved', 'Resolved')], default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=5),
        ),
    ]
