# Generated by Django 6.1 on 2026-08-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
