# Generated by Django 6.1 on 2026-09-27 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField()),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('ROOM', 'Room'), ('OFFICE', 'Office')], db_index=True, max_length=20)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathroom', models.PositiveSmallIntegerField(default=1)),
                ('availability_status', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
                'permissions': [('can_publish_property', 'Can publish property')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location', 'property_type'], name='properties__locatio_3dbc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
    ]
