# Generated by Django 6.1.1 on 2026-09-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-created_at',), 'permissions': [('can_publish_property', 'Can publish property')], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
